chore: Update service binding docs
SAP/ai-sdk-js pull request #279
Opened 2024-11-08 11:52 UTC by deekshas8

## Context

AI/gen-ai-hub-sdk-js-backlog#157.

Update README to include a note about AI SDK handling of ai core service binding

## Definition of Done

- [ ] Code is tested (Unit, E2E)
- [ ] Error handling created / updated & covered by the tests above
- [ ] Documentation updated
- [ ] (Optional) Aligned changes with the Java SDK
- [ ] (Optional) Release notes updated

2024-11-08 14:23 UTC, MatKuhr reviewed
otherwise lgtm

2024-11-08 14:23 UTC, MatKuhr commented on packages/foundation-models/README.md
> +  - Use the [`DeploymentApi`](https://github.com/SAP/ai-sdk-js/blob/main/packages/ai-api/README.md#create-a-deployment) from `@sap-ai-sdk/ai-api` to deploy a model to the SAP Generative AI Hub. For m
```suggestion
  - Use the [`DeploymentApi`](https://github.com/SAP/ai-sdk-js/blob/main/packages/ai-api/README.md#create-a-deployment) from `@sap-ai-sdk/ai-api` to deploy a model to the SAP Generative AI Hub.
  For more information, see [this guide](https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/create-deployment-for-generative-ai-model-in-sap-ai-core).
```

2024-11-08 14:23 UTC, MatKuhr commented on packages/foundation-models/README.md
> +> The SDK automatically retrieves the `AI Core` service binding from the `VCAP_SERVICES` environment variable, along with the service token needed for authentication.
```suggestion
> The SDK automatically retrieves the `AI Core` service credentials from the `VCAP_SERVICES` environment variable and resolves the access token needed for authentication.
```

2024-11-08 15:43 UTC, jjtang1985 commented on packages/ai-api/README.md
> +- Configure the project with **Node.js v20 or higher** and **native ESM** support.
I can see many copy/pasted content for different packages :)

2024-11-08 15:45 UTC, jjtang1985 requested changes
LGTM in general.
Please consider adding the doc for the Launchpad scenario.

2024-11-11 07:00 UTC, deekshas8 commented on packages/foundation-models/README.md
> +  - Use the [`DeploymentApi`](https://github.com/SAP/ai-sdk-js/blob/main/packages/ai-api/README.md#create-a-deployment) from `@sap-ai-sdk/ai-api` to deploy a model to the SAP Generative AI Hub. For m
Updated in all READMEs

2024-11-11 07:00 UTC, deekshas8 commented on packages/foundation-models/README.md
> +> The SDK automatically retrieves the `AI Core` service binding from the `VCAP_SERVICES` environment variable, along with the service token needed for authentication.
Updated in all READMEs

2024-11-11 07:12 UTC, deekshas8 commented on packages/foundation-models/README.md
> +- Ensure a deployed OpenAI model is available in the SAP Generative AI Hub.
Done

2024-11-11 07:59 UTC, jjtang1985 approved these changes

2024-11-11 08:03 UTC, merged