feat: Update to Orchestration 0.36.1
SAP/ai-sdk-js pull request #333
Opened 2024-11-29 10:51 UTC by MatKuhr

## Context

SAP/gen-ai-hub-sdk-js-backlog#

## Definition of Done

- [x] Code is tested (Unit, E2E)
- [x] Error handling created / updated & covered by the tests above
- [x] ~Documentation updated~
- [x] (Optional) Aligned changes with the Java SDK
- [ ] (Optional) Release notes updated

2024-11-29 10:55 UTC, MatKuhr commented on packages/foundation-models/src/azure-openai/client/inference/schema/audio-response.ts
> + * Translation or transcription response when response_format was json
Not sure where these changes are coming from TBH

2024-11-29 10:57 UTC, MatKuhr commented on packages/orchestration/src/orchestration-response.ts
> +    return this.data.orchestration_result.usage!;
This is fine to do because this is only undefined in case of streaming. To be fixed in the spec

2024-11-29 14:03 UTC, ZhongpinWang commented on packages/foundation-models/src/azure-openai/client/inference/schema/citation.ts
> + * citation information for a chat completions response message.
Question mark. 👀

2024-11-29 14:03 UTC, ZhongpinWang commented on packages/foundation-models/src/azure-openai/client/inference/schema/azure-chat-extension-configuration.ts
> + *   A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat
Question mark. 👀 What happened in the doc. Why do we have indentation here..

2024-11-29 14:04 UTC, ZhongpinWang commented
Should we wait until the next released spec version, where they remove `help.sap.com`?

2024-11-29 15:47 UTC, MatKuhr commented
> Should we wait until the next released spec version, where they remove `help.sap.com`?

Updated 👍🏻

2024-12-03 10:42 UTC, ZhongpinWang requested changes
[req] Why are we regenerating azure openai client? I think maybe you hit the `pnpm generate`. Not sure why these changes are there but since they are all ugly, maybe we should run `pnpm orchestration generate` instead to also keep this PR clean?

2024-12-03 11:34 UTC, MatKuhr commented
Yeah I just ran generate, so the azure changes were a side effect of the pipeline currently not enforcing re-generation. Reverted now.

2024-12-03 12:05 UTC, ZhongpinWang commented
[q] Do we still need to exclude template ref?

2024-12-03 12:14 UTC, MatKuhr commented
> [q] Do we still need to exclude template ref?

What do you mean? It currently isn't exported because it's not tested..

2024-12-03 12:16 UTC, ZhongpinWang commented
> > [q] Do we still need to exclude template ref?
> 
> What do you mean? It currently isn't exported because it's not tested..

Oh misread. It is not exported. Ignore this.

2024-12-03 12:17 UTC, merged