chore: Add filter utility to improve discoverability
SAP/ai-sdk-js pull request #72
Opened 2024-08-15 13:03 UTC by KavithaSiva

This PR introduces `FilterUtility` to make new functionality being added to filter configuration like for e.g a new service provider discoverable.

Proposed state:
```Typescript
client.chatCompletion({
  deploymentConfiguration: { deploymentId: 'id' },
  llmConfig: {
    model_name: 'gpt-35-turbo-16k',
    model_params: { max_tokens: 50, temperature: 0.1 }
  },
  prompt: {
    template: [{ role: 'user', content: 'What is the capital of Germany?' }]
  },
  filterConfig: {
     //Both options are allowed
    input: FilterUtility.azureContentFilter({ Hate: 4, SelfHarm: 2 }), 
    output: azureContentFilter({ Sexual: 0, Violence: 6 })
  }
});
```

2024-08-16 10:08 UTC, tomfrenken commented
I like the idea of improved discoverability, however, I really dislike long call chains (e.g. `MyCoolClass.someFunctionForSomething()`) therefore I would be in favor of adding a dedicated section for our filter function(s) as they grow.

2024-08-16 10:11 UTC, tomfrenken commented
On the other hand, depending on how the different filters will be chained together, we might even consider a similar implementation to the cloud sdk's resilience package: https://sap.github.io/cloud-sdk/docs/js/guides/resilience

2024-08-16 12:32 UTC, KavithaSiva commented
> On the other hand, depending on how the different filters will be chained together, we might even consider a similar implementation to the cloud sdk's resilience package: https://sap.github.io/cloud-sdk/docs/js/guides/resilience

Could you sketch out an example on how this would look?

2024-08-19 07:28 UTC, jjtang1985 commented on packages/gen-ai-hub/src/orchestration/orchestration-client.test.ts
> +        output: FilterUtility.azureContentFilter({ Sexual: 0, Violence: 4 })
I prefer the original API.

2024-08-19 08:13 UTC, jjtang1985 requested changes
I prefer the original API, which is short and JS native.

2024-08-19 08:39 UTC, closed without merging