feat: API Visibility
SAP/ai-sdk-js pull request #81
Opened 2024-08-19 22:27 UTC by shibeshduw

DRAFT

Closes: [AI/gen-ai-hub-sdk-js#16](https://github.tools.sap/AI/gen-ai-hub-sdk-js-backlog/issues/16)

2024-08-22 14:01 UTC, marikaner requested changes
I am missing a script that checks the correctness of this or do we already have that? See: https://github.com/SAP/cloud-sdk-js/blob/main/scripts/check-public-api.ts and other files around that

2024-08-23 07:21 UTC, shibeshduw commented on packages/core/package.json
> +    "lint:fix": "eslint \"**/*.ts\" --fix && prettier . --config ../../.prettierrc --ignore-path ../../.prettierignore -w --log-level error"
Yes the `check-public-api.ts` was the script that had the typescript version dependency clash with the one in the cloud-sdk-js. Now that the version is updated, i will add the script back. 

I tried the `--ext` eslint option before pushing this and I believe this option is invalid for the current version of eslint we are using.

2024-08-23 12:27 UTC, marikaner commented
@shibeshduw please add the check on a separate PR, I think this will be easier to review. Don't forget to adjust the description in here.

2024-08-23 12:28 UTC, marikaner submitted a review, later dismissed
👍

2024-08-23 12:32 UTC, marikaner approved these changes

2024-08-23 12:34 UTC, merged